version: '2'

services:
    nginx:
      image: jbmarflo/docker-web:nginx
      build:
        context: ./docker/nginx/
    cli:
      image: jbmarflo/docker-web:cli
      build:
        context: ./docker/php-fpm/
#    elasticsearch_1:
#      image: elasticsearch_project:5.6.1
#      build:
#        context: ./docker/elasticsearch/
#      image: elasticsearch_project:5.6.1
#      build:
#        context: ./docker/elasticsearch/

#    composer:
#      build: docker/composer/
#      volumes:
#        - ./app/:/var/www/html