# https://github.com/elastic/elasticsearch-docker
FROM composer/composer:php7

#VOLUME ["./app/", "/var/www/html"]
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
